spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: C##VISHAL
    password: VISHAL
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

jwt:
  secret: change_this_to_a_long_random_string_with_32+_bytes
  expiration-ms: 86400000
